### ISSUE TITLE
JS version generates incorrect diff when there are more than 2^16-1 unique lines

### ISSUE THREAD

**Issue by alur** [google/diff-match-patch#11]

**Comment by NeilFraser** [comment]
In this case, don't use the line-mode speedup.  Set opt_checklines to false when calling diff_main:

https://github.com/google/diff-match-patch/blob/master/javascript/diff_match_patch_uncompressed.js#L78

Leaving this issue open so that I can look at it later and see if we can autodetect this failure case and disable the speedup if it will fail.

**Comment by NeilFraser** [comment]
Fixed in all languages except Lua (which is immune since it doesn't support Unicode).
Thanks!  I think this is the first corrupt diff bug in ten years.

**Comment by alur** [comment]
Thank you for addressing it so quickly! :)

**Comment by NeilFraser** [comment]
Fixed a second time.  This time it allocates 2/3rds of the available Unicode space to text1, and the remaining 1/3rd to text2.  That means that the start of both texts should benefit from the line-mode speedup, rather than have text1 hog the entire space and text2 be reduced to a single symbol.
