### ISSUE TITLE
Does not seem to work with big text

### ISSUE THREAD

**Issue by kylak** [google/diff-match-patch#123]
Hi tried to compare two ancient greek codices of the New Testament but it seems to failed since for the Vaticanus and Sinaiticus I only have βιβλοϲγενεϲεωϲ|ιυ||χυ|υιου as common bloc.

**Comment by dmsnell** [comment]
@kylak for long texts the library resorts to line-by-line diffing, meaning that if even one letter is different between any two lines (that are in the same position in the two documents) then it will return as different.

this is a speedup because of practical issues with performance. you should be able to recompute passing overrides to the `checklines` and `timeout` arguments. if using the JavaScript library this should be `diff_main(vaticanus, sinaticus, false, Infinity)`

Note too that this is a raw text-diffing library and unaware of semantic equivalence or difference. `η` and `ή` for example should be identified as different even though both are linguistically equivalent in this case. Similarly be aware of Unicode-encoding issues, as things like `ή` and `ή` exist which represent the same character but are formed through different constructions (in this case one is the eta with the acute accent and the other is an eta followed by a combining acute accent).

**Comment by kylak** [comment]
I see thanks, actually my text is a monolithic bloc of thousands and thousands and thousands of characters without any spaces or line return, so it analyses the whole text as one line, I think it would take years and years and years for my computer to find the differences. And yes I formatted the greek texts to have only "simples" characters (no accents, no uppercase, etc.). Looks like I'll have to look for a new solution.

**Comment by dmsnell** [comment]
@kylak very good. it probably gave up due to the timeout then is my guess.

@NeilFraser we can probably close this issue now.
