### ISSUE TITLE
Non-minimal diff returned for some inputs

### ISSUE THREAD

**Issue by marijnh** [google/diff-match-patch#131]
If you compute `diff_main("dbabcddb", "babcbabc")`, the library will pick the wrong half match in `diff_halfMatch` and come up with a non-minimal diff (del `d`, ins `babc`, keep `babc`, del `ddb`). If you flip the arguments it doesn't have the problem. It looks like the library does intend to return minimal diffs.

**Comment by dmsnell** [comment]
@marijnh `diff-match-patch` intentionally does not intend to return minimal diffs. the modified diffing algorithm trades that goal for efficiency/speed, and the cleanup passes after finding an edit script directly modify that script to be more _human-readable_. the line-level diffing mode similarly prevents any practical way to find the shortest edit script because it doesn't analyze intra-line diffs.

if you see something suggesting that it intends to return shortest edit script diffs then we might need to clarify that language; can you share a link to where you saw it?

if you need minimal diffs you will likely need another library, but be aware that can be a quadratic process or worse and only gets more problematic with long documents, something any general-purpose library is going to struggle with.

**Comment by marijnh** [comment]
All right, I'll close this then.
