### ISSUE TITLE
Compatibility of the diff-match-patch

### ISSUE THREAD

**Issue by srini1978** [google/diff-match-patch#35]
Have a couple of questions with respect to library
1. Does it work with IE 11, Edge, Chrome?
2. Does it support rich text comparison with non-English languages  - German  etc. If so is there a list of languages it supports.
3. Does it support comparison if the rich text that i am comparing has tags within it ?
4. The text that i am getting from the database has html in it <b><textarea> this is my name </textarea></b> . It has to be compared with <b><textarea> this is not my name and it is not library</textarea></b>. The comparison should compare only the text piece if it.
5.

**Comment by NeilFraser** [comment]
> Does it work with IE 11, Edge, Chrome?

From the [JS docs](https://github.com/google/diff-match-patch/wiki/Language:-JavaScript): "It works in Netscape 4, Internet Explorer 5.5, and all browsers released since the year 2000 (the limiting factor is the use of the encodeURI function)."

As for rich text and non-English, Diff Match Patch doesn't care.  This library works on anything that can be represented in Unicode.  So HTML, RTF, or other formats are all fine.  That said, if the matches and patches are fuzzy, then structured content may be generated that isn't valid.  See [Plain Text vs. Structured Content](https://github.com/google/diff-match-patch/wiki/Plain-Text-vs.-Structured-Content) for more information.
