### ISSUE TITLE
dart version have something wrong, please fix it...

### ISSUE THREAD

**Issue by liuzhengdong2** [google/diff-match-patch#65]
like
	"message": "'Diff.==' ('(Diff) → bool') isn't a valid override of 'Object.==' ('(dynamic) → 

	"message": "A value of type 'Operation' can't be assigned to a variable of type 'int'.",
	"startColumn": 27,
	"endColumn": 54,
...

**Comment by NeilFraser** [comment]
This is why I hate Dart.  Code that works one month, doesn't work the next month.  APIs change, syntax changes, everything is in a constant state of flux.

I'll update the Dart port of the DMP library once again...

**Comment by NeilFraser** [comment]
Dart is now working.

Leaving this issue open, since there are still two problems:
1. The unit tests don't run since Dart's package rules have changed.  If the code is hacked to bypass this, the unit tests all pass.  But I need to find a different way to run tests on private methods.
2. The dart2js speedtest just crashed from 1.6 seconds to 25 seconds.  Don't know why, there are no changes in the library.  The dart VM speedtest is unchanged.

**Comment by NeilFraser** [comment]
Unit tests now run.

**Comment by liuzhengdong2** [comment]
I notice that 'diff_match_patch 0.3.0'  plugin is still working, so I use that. 
I also think the 0.3.0's API is too simple for use, like no translator to HTML. But that's not a big problem.
Eventually Thank you for you fix  : )

**Comment by NeilFraser** [comment]
The dart2js speedtest can be brought down to 0.9 seconds with the -O4 command-line flag.  Analysis showed that under the default options it was spending most of its time doing type checking.

Everything resolved.  Closing issue.
