### ISSUE TITLE
The result of the patch is strange.

### ISSUE THREAD

**Issue by LeeChungWan** [google/diff-match-patch#66]
![image](https://user-images.githubusercontent.com/26535056/56634486-20574680-669d-11e9-940a-cd4c64981a1c.png)

I want the result of `<div>ba</div>` when I apply the above patch to `<div>b</div>`.

However, the result only displays `<div>a</div>` as shown below.

Is this correct?

![image](https://user-images.githubusercontent.com/26535056/56644463-afbd2380-66b6-11e9-9025-6e103b928a02.png)

**Comment by NeilFraser** [comment]
That output is correct.  Patch only includes a few characters of context, not the entire text.

If you go to the patch demo at https://neil.fraser.name/software/diff_match_patch/demos/patch.html and enter:
`abcdefghijklmnopqrstuvwxyz`
and
`abcdefghijklmXXXnopqrstuvwxyz`
as the two texts, then press "Compute Patch" the result should be:

```
@@ -6,16 +6,19 @@
 fghijklm
+XXX
 nopqrstu
```

For the entire text, you'd want to use diff instead of patch.  If you go to the diff demo at https://neil.fraser.name/software/diff_match_patch/demos/diff.html and enter:
`abcdefghijklmnopqrstuvwxyz`
and
`abcdefghijklmXXXnopqrstuvwxyz`
as the two texts, then press "Compute Patch" the result should be:

```
abcdefghijklm_XXX_nopqrstuvwxyz
```
(Sorry, GitHub's markdown doesn't render this properly, but you get the idea.)
